version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/app/dist
    environment:
      - VITE_MAIN_SSO=https://sso.joltamp.pl
      - VITE_MAIN_BACKEND=
    command: sh -c "npm run build"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - frontend
    volumes:
      - ./frontend/dist:/app/www
    environment:
      - ROCKET_ENV=prod
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - JWT_SECRET=JQWtt4NvvE20nvKfHAWcTmkQ5q9KlkK1IrQjSTLDYUOjpohmN4
    ports:
      - "8001:8000"
    command: ./backend

volumes:
  frontend-dist: